header:
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0'
key_words:
  - Age Care
  - Domestic Assistance
  - Personal Care
  - Nursing
  - Homecare package
  - Support Workers
  - Career
  - Support Coordination
  - NDIS
  - Plan management
social_links:
  - linkedin
  - facebook
  - instagram
email_link_identifier: 'mailto:'
phone_link_identifier: 'tel:'